### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by LorenzHenk**
- [x] advanced
- [ ] api
- [x] builder
- [ ] faq
- [ ] get started
- [x] home
- [x] nav

### CODE REVIEW

**Comment by bluebill1049** [comment]
wow thanks very much for translating the docs into German ❤️

**Comment by bluebill1049** [comment]
hey @LorenzHenk I know you must be busy and I am not here to hassle you to get the translate complete, just a friendly reminder that hopefully these good work doesn't get wasted and forgotten :) ❤️ (whenever you have some more freetimes) 

thanks very much
bill

**Comment by Paquan** [comment]
So... I'm a little lost right now. What should I do to help with german translation.

**Comment by bluebill1049** [comment]
hmmm @Paquan thanks a lot of the follow up. looks like this PR is way behind of master, probably easier just start a brand new PR and port some of @LorenzHenk's work over instead to mess with all those conflicts.

**Comment by bluebill1049** [comment]
nvm let's pause this for awhile

**Pull request closed without merging**
