### PR TITLE
Improve english grammar

### PR DESCRIPTION
**Pull request by barrymay**
@bluebill1049 I absolutely love the look of website, but I have felt that the English grammar needs some help :). I hope this helps.  Please run it and let me know if you find any problems or concerns.

Since I may need to reduce my involvement in react-hook-form in the next few weeks, I really wanted to do this to help out.

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks heaps @barrymay feel free to jump in and out (for this lib). I completely understand if you are busy over your real* work :) again much appreciated your help over the lib and everything.

**Comment by barrymay** [comment]
I have not modified any of the code examples - just the text around them.  

In some cases I saw bugs where text wasn't correctly placed on the page, this should correct that.

**Comment by barrymay** [comment]
(not sure why the deployment failed.. let me know if you need any help on that)

**Comment by bluebill1049** [comment]
all good fixed @barrymay it's node version under now deploy

**Comment by barrymay** [comment]
Oops sorry bout that - thx for correcting!

**Pull request merged**
