### PR TITLE
Spanish language translation

### PR DESCRIPTION
**Pull request by cargallo**
Hi @bluebill1049 I added the spanish language translation! I think that I modified all the required files, but to be sure please check it. I will try to get someone who can double check if I mistranslated any expression. Cheers!

### CODE REVIEW

**Comment by bluebill1049** [comment]
amazing work and effort big 👍 thank you ❤️

**Comment by cargallo** [comment]
> amazing work and effort big 👍 thank you ❤️

Thank you! I'm new in React's world, mostly I have java background. I am begining as freelance dev after 15 years of working inside a pharmaceutical company. Glad to help in my free time and involving in frontend projects!

**Comment by bluebill1049** [comment]
> > amazing work and effort big 👍 thank you ❤️
> 
> Thank you! I'm new in React's world, mostly I have java background. I am begining as freelance dev after 15 years of working inside a pharmaceutical company. Glad to help in my free time and involving in frontend projects!

Welcome to the React Community (JS) ✌️Awesome to have people like yourself willing to contribute and spend their free time to help everyone else. ❤️🥂I start working on open source about 2 years ago, before that i am most just using open source projects and hardly contribute back to the community. Now it's becoming my passionate and hobbit. The feeling of helping devs around the world is great and I can't never find or achieve that in the work place.

**Comment by bluebill1049** [comment]
feel free to merge when you are comfortable (it will straight way go production)

**Comment by bluebill1049** [comment]
Do you have a Twitter account so i can tag you?

**Comment by cargallo** [comment]
I just added you 20 minutes ago @cargallodev
Tomorrow I check everything again and make the merge. I'm falling asleep on the keyboard, it's 2 am now in Argentina 😴

**Comment by bluebill1049** [comment]
have a good night 🌛followed you in Twitter too : )

**Comment by cargallo** [comment]
Hi @bluebill1049 I don't have access to make the merge. I review the code and I think it is ready.

**Comment by bluebill1049** [comment]
Thank you very much @cargallo LIVE ✌🏻

**Pull request merged**
