### PR TITLE
Improved ApiPage bundle size

### PR DESCRIPTION
**Pull request by keiya01**
I improved bundle size. To improve bundle size, I moved the file that loads the data from ApiPage to the page for each language.

But other pages are loaded data file on common pages too. 
Is there a reason for this ?

See the fallowing images for the bundle size.

Before:

スクリーンショット 2020-05-31 19 31 14

After:

スクリーンショット 2020-05-31 19 33 53

### CODE REVIEW

**Comment by bluebill1049** [comment]
That's really awesome! 🥳  🥳  🥳 

Could I please ask you a big favor? Could we please apply those changes to V6 branch to avoid all the conflicts in the next week? we are going to release v6 in 2 weeks' time.

if you are busy, that's fine as well. feel free to merge it in!

> But other pages are loaded data file on common pages too.
> Is there a reason for this ?

should totally do for other pages as well, i will come to them.

**Comment by keiya01** [comment]
No problem! I'll try fixing the conflict :)

**Comment by bluebill1049** [comment]
ty very much.

**Comment by bluebill1049** [comment]
Too good! thank you again!

**Pull request merged**
