### PR TITLE
docs: improve English in Advanced

### PR DESCRIPTION
**Pull request by dandv**
Sorry about the first commit, which I had previously submitted via a separate PR. I was editing from GitHub's UI.

### CODE REVIEW

**Comment by bluebill1049** [comment]
that's all good mate :) thanks for those improvements in English! As you can tell, English is not my native languages, any adjustment and improvement are more than welcome.

**Comment by dandv** [comment]
I don't know, was it you who narrated the videos? That English was great!

**Comment by bluebill1049** [comment]
> I don't know, was it you who narrated the videos? That English was great!

which video?

**Comment by dandv** [comment]
The [wizard](https://react-hook-form.com/advanced-usage#WizardFormFunnel) one

**Comment by bluebill1049** [comment]
> The [wizard](https://react-hook-form.com/advanced-usage#WizardFormFunnel) one

Oh thanks, @dandv that's me.

**Pull request merged**
