### PR TITLE
Improve side menu

### PR DESCRIPTION
**Pull request by JeromeDeLeon**

### CODE REVIEW

**Comment by bluebill1049** [comment]
awesome thanks @JeromeDeLeon ! that was a lovely fix!. now the website looks much better with that scroll bar!

**Comment by JeromeDeLeon** [comment]
I would also like to change the overall scrollbar design to match the side menu scrollbar, but I will leave that to your decision. 😄

**Comment by bluebill1049** [comment]
do it when you have time! @JeromeDeLeon  keep it consist

**Comment by bluebill1049** [comment]
lovely work!

**Pull request merged**
