### PR TITLE
Add JSON.stringify()

### PR DESCRIPTION
**Pull request by WilcoBreedt**
Add JSON.stringify to prevent React Native error `Value for message cannot be case from ReadableNativeMap to String` when running `onSubmit` function

### CODE REVIEW

**Comment by WilcoBreedt** [comment]
Hi, I see there are a few guidelines when submitting a PR that I missed. You can close the PR and I will adhere to the guidelines and create another PR in the case that it is a problem

**Comment by bluebill1049** [comment]
Thank you mate :)

**Comment by bluebill1049** [comment]
It's fine 👍 thanks for contributing.

**Comment by WilcoBreedt** [comment]
Great thanks! Happy to help

**Pull request merged**
